[workspace]
members = [
  "core",
  "proxy",
  "shared",
  "shell",
]
resolver = "2"

[workspace.metadata]
project_name = "selvedge"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
repository = "https://github.com/thmasq/selvedge"
description = "Web-based Matrix client with multi-threaded WASM architecture"

[workspace.dependencies]
console_error_panic_hook = "0.1.7"
eyeball-im = "0.8.0"
futures = "0.3.32"
getrandom = { version = "0.3", features = ["wasm_js"] }
gloo-console = "0.3.0"
gloo-storage = "0.3.0"
gloo-timers = { version = "0.3.0", features = ["futures"] }
gloo-worker = "0.5.0"
indexmap = "2.13.0"
js-sys = "0.3.85"
leptos = { version = "0.8.15", features = ["csr"] }
matrix-sdk = { version = "0.16", default-features = false, features = ["js", "indexeddb", "e2e-encryption", "rustls-tls", "qrcode"] }
matrix-sdk-ui = { version = "0.16.0", default-features = false, features = ["rustls-tls", "js"] }
mime = "0.3.17"
ruma = { version = "0.14.1", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
wasm-bindgen = "0.2.108"
wasm-bindgen-futures = "0.4.58"
web-sys = { version = "0.3.85", features = ["ServiceWorkerGlobalScope", "FetchEvent", "Cache", "CacheStorage", "Request", "Response"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
