[package]
name = "selvedge-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
getrandom = { workspace = true }
gloo-console = { workspace = true }
gloo-timers = { workspace = true }
gloo-worker = { workspace = true }
indexmap = { workspace = true }
js-sys = { workspace = true }
matrix-sdk = { workspace = true }
ruma = { workspace = true }
selvedge-shared = { path = "../shared" }
serde = { workspace = true, features = ["derive"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
