[package]
name = "selvedge-core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
selvedge-shared = { path = "../shared" }
matrix-sdk = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
gloo-console = { workspace = true }
gloo-timers = { workspace = true }
gloo-worker = { workspace = true }
ruma = { workspace = true }
js-sys = { workspace = true }
